### ISSUE TITLE
Latest snapshot (0.1.2.0-68-g0f02eca) freezes computer

### ISSUE THREAD

**Issue by zupalex** [Alia5/GlosSI#226]
## Expected Behavior
GlosSITarget starts normally

## Actual Behavior
After GlosSITarget starts and the overlay display shortly, computer freezes completely and does not respond to any input from mouse of keyboard.

This does not happen with the latest stable release.

## Steps to Reproduce the Problem

  1. Install snapshot 0.1.2.0-68-g0f02eca
  2. Add GlosSI-target as non-steam game to steam
  3. Click "play" with or without a controller connected

## General Information

  - Version: 0.1.2.0-68-g0f02eca
  - Platform: Win10 Desktop
  - Controller(s): irrelevant, does it with no controller attached, xbox controller attached or joycons pair attached
  - Application: GlosSITarget

## Logs / Additional Files

[glossitarget.log](https://github.com/Alia5/GlosSI/files/12250138/glossitarget.log)
[GlosSIWatchdog.log](https://github.com/Alia5/GlosSI/files/12250139/GlosSIWatchdog.log)
[UWPOverlayEnabler.log](https://github.com/Alia5/GlosSI/files/12250140/UWPOverlayEnabler.log)
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/12250141/glossiconfig.log)

**Comment by zupalex** [comment]
Thanks for the reply. What is the relevant info I should include for them if I raise an issue there?

**Comment by RADIOACTIVEshrek** [comment]
> Probabla an Issue for https://github.com/ViGEm/ViGEmBus/issues

Providing actual support would probably help, then, rather than just closing immediately with a vague statement.
Having the same issue here, can't find any info on fixing it.
As for further information, this happens on any behavior with this snapshot build. The build is simply broken. If the problem is with ViGEmBus, then provide a proper way to introduce the problem, instead of lazily responding.

**Comment by Alia5** [comment]
> Providing actual support would probably help, then, rather than just closing immediately with a vague statement. Having the same issue here, can't find any info on fixing it. As for further information, this happens on any behavior with this snapshot build. The build is simply broken. If the problem is with ViGEmBus, then provide a proper way to introduce the problem, instead of lazily responding.

Paying me to do the actual support instead of complaining that I don't work for free in my spare time, for a software product that is essentially gifted to you, would actually help.
Let alone that I cannot provide support for dependencies that I'm merely using.

You are out of your mind.

/ Torvalds Mode End

**Comment by zupalex** [comment]
Firstly, let me state that I appreciate the efforts in maintaining such a nice piece of work for free and offering this to the community.

Just a naive question: the version of the dependency you use in the current stable build does not cause this behaviour. Couldn't you revert to using that version in the latest snapshot rather than using the broken one?
