### ISSUE TITLE
Steam Overlay Not Visible

### ISSUE THREAD

**Issue by Funky7Monkey** [Alia5/GlosSI#98]
While attempting to use GloSC for desktop menus, I found that the Steam Overlay is not visible through GloSC. The overlay "works," menus function as intended, etc, however none of the overlay is visible.

I am on Windows 10 Build 18362, with the latest version of the Steam Client. It seems to be a problem caused by a client update, but I have not had issues with non-Steam games using the overlay. I've seen multiple people with this issue on Discord, using GloSC for the desktop or for other games.

**Comment by Alia5** [comment]
Is the big picture overlay enabled?

**Comment by mediumgoose** [comment]
Hey, I was having the exact same issue and was actually talking to OP on the discord. Everything works, if I press the main steam button I open the overlay (I can hear it when I move the joystick), but the overlay is invisible. Steam overlay / big picture overlay is enabled in the main steam settings / BPM settings, and the GloSC shortcuts' individual controller settings.

**Comment by CMLL** [comment]
I'm running in a similar issue with Windows Store games. Tried it with Gears 4, Rage 2 and The Outer Worlds, game pass version. All present the same behaviour. If you select windowed fullscreen or borderless the overlay shows, if you select exclusive fullscreen it doesn't. I believe is the same thing that was happening with Destiny 2 on Battlenet.

**Comment by dglt1** [comment]
has anyone made progress on this issue?  it just started for me a few days ago, i've tried with/without BPM overlay. did a clean install of both ViGem and GloSC and i've tried steam stable and steam beta but the problem remains.

- setting from steam controller config before launching GloSC and controller outputs work as they should but not the overlay. if i hit the steam button for the overlay i can hear the overlay sounds but  nothing is visible.

is there an opacity configuration anywhere i could try to play with and see if it helps?

**Comment by OfficerHalf** [comment]
For me the issue is present regardless of fullscreen/windowed. As far as I know there's been no movement here; it seems to be a fairly uncommon issue.

**Comment by Jdbye** [comment]
I have this issue with Hellblade: Senua's Sacrifice. I would expect the overlay not to show up in fullscreen mode, as fullscreen mode is by its nature exclusive and you would have to hook into the game in much the same way the overlay normally does to make that work (and that is why the overlay is not just a borderless window to begin with, it wouldn't work for every scenario)
But it doesn't work regardless of fullscreen or windowed mode in that game. It works just fine in Subnautica though, so it must be something specific to certain games. Being able to use the overlay and change controller mappings on the fly is nice, but it's not a must for me, it's not what I downloaded GloSC for, it's just a nice bonus. Maybe the issue is that the game is also set as on top and takes priority over the overlay? It doesn't seem like there is a way to change the Z order so the overlay takes priority though, so a fix would probably involve some sort of workaround.

**Comment by a7lan** [comment]
I have the same problem. Black screen. But if you press the alt tab, you can switch to the game. But then the encoder is DWM NV12 and only 30 fsp. It is impossible to play. Although steamlink says about 60 fps. Problem with fullscreen and windowed mode. 

My pc. Windows 10 1809. Ryzen 3600 + Radeon 5700
Client. Raspberry 4. Raspbian, last version steamlink.

**Comment by Jdbye** [comment]
> 
> 
> I have the same problem. Black screen. But if you press the alt tab, you can switch to the game. But then the encoder is DWM NV12 and only 30 fsp. It is impossible to play. Although steamlink says about 60 fps. Problem with fullscreen and windowed mode.
> 
> My pc. Windows 10 1809. Ryzen 3600 + Radeon 5700
> Client. Raspberry 4. Raspbian, last version steamlink.

Unrelated issue. This will not make Steam hook into the game, there is no way to do that as far as I know because Store apps are sandboxed and isolated from other programs. It's only a workaround for Steam Overlay and controller support. Instead of hooking into the game Steam hooks into a transparent window that GloSC creates so that transparent window is what gets captured when you try to use Steam Link. Other methods of game streaming such as Nvidia Gamestream / Moonlight or Parsec might work with Store apps, but Steam specifically relies on being able to hook into the game.

**Comment by a7lan** [comment]
I have this problem with any game. At startup, a black screen. Checked now for Dirt 3. Black screen. But if you press the alt tab, you can return the image.

**Comment by sonw666** [comment]
same, black screen

**Comment by Alia5** [comment]
Can you try https://github.com/Alia5/GlosSI/releases/tag/0.0.2.0
